<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_list</name>
   <tag></tag>
   <elementGuidId>a508cebe-975b-419b-98a6-e53d38b38123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='page_body']/descendant::select[${rowNo}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='page_body']/descendant::select[${rowNo}]</value>
   </webElementProperties>
</WebElementEntity>
